In [1]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.

# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.

# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.

# 4. Create a tf.Variable with initial value 5.0 and print its current value.

# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.

# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.

# 7. Create a variable x = 3.0 and inside a tf.GradientTape() block compute y = x**2 + 2*x + 1, then print both x and y.

# 8. Compute the gradient dy/dx for y = x**2 + 2*x + 1 using tf.GradientTape() and print the gradient value.

# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().

# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.


In [2]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
import tensorflow as tf

scalar = tf.constant(10) 
print(f"Scalar value: {scalar.numpy()}")
print(f"Scalar datatype: {scalar.dtype}")

Scalar value: 10
Scalar datatype: <dtype: 'int32'>


In [3]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
vector = tf.constant([2,4,6,8])
print(f"Vector shape: {vector.shape}, values: {vector.numpy()}")


Vector shape: (4,), values: [2 4 6 8]


In [4]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
matrix = tf.constant([[1, 2], [3, 4]]) 
print(f"Matrix shape: {matrix.shape},datatype:{matrix.dtype}")

Matrix shape: (2, 2),datatype:<dtype: 'int32'>


In [5]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.

value= tf.Variable(5.0,name="value")
print(f"Initial value:{value.numpy()}")


Initial value:5.0


In [7]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
value.assign(10.0)
print(f"Updated value {value.numpy()}")

Updated value 10.0


In [10]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.

weights = tf.Variable([[1.0, 2.0], [3.0, 4.0]], name="weights")
weights.assign_add([[1.0, 1.0], [1.0, 1.0]])
print(f"Updated weights:\n{weights.numpy()}")

Updated weights:
[[2. 3.]
 [4. 5.]]


In [11]:
# 7. Create a variable x = 3.0 and inside a tf.GradientTape() block compute y = x**2 + 2*x + 1, then print both x and y.

x=tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x ** 2 + 2 * x + 1 
print(x,"\n",y)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0> 
 tf.Tensor(16.0, shape=(), dtype=float32)


In [12]:
# 8. Compute the gradient dy/dx for y = x**2 + 2*x + 1 using tf.GradientTape() and print the gradient value.
x=tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x ** 2 + 2 * x + 1 
dy_dx= tape.gradient(y,x)

print("x =", x.numpy())
print("y =", y.numpy())
print("dy/dx =", dy_dx.numpy())    

x = 3.0
y = 16.0
dy/dx = 8.0


In [13]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
mul=tf.matmul(a,b)
print("Matrix a:\n", a.numpy())
print("Matrix b:\n", b.numpy())
print("Matrix multiplication result:\n", mul.numpy())

Matrix a:
 [[1 2]
 [3 4]]
Matrix b:
 [[5 6]
 [7 8]]
Matrix multiplication result:
 [[19 22]
 [43 50]]


In [15]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.

random_tensor= tf.random.uniform(shape=(3,3))
print(f"shape : {random_tensor.shape}")
print(f"Datatype : {random_tensor.dtype}")
print(f"Values : {random_tensor.numpy()}")

shape : (3, 3)
Datatype : <dtype: 'float32'>
Values : [[0.28720593 0.19890034 0.39534032]
 [0.25075662 0.9962065  0.25097656]
 [0.82695043 0.20385289 0.29919994]]
